### ISSUE TITLE
sponsor directly through github

### ISSUE THREAD

**Issue by seanjensengrey** [AbstractMachinesLab/caramel#2]
I am unable and now unwilling to sponsor through patreon, furthermore direct github sponsorships do not take a cut.

I'd like to give you 20$/month to support this project.

**Comment by ostera** [comment]
Hej @seanjensengrey, oh wow, thanks a million! I'm waiting on verification from the Github staff :) I'll ping you when the option is available.

**Comment by ostera** [comment]
Aaand we're go on the Github Sponsors setup! ✔️

**Comment by seanjensengrey** [comment]
Thanks so much! Done.
