### ISSUE TITLE
Refactor Erlang AST and Parser to carry location information

### ISSUE THREAD

**Issue by ostera** [AbstractMachinesLab/caramel#25]
In order to provide good error messages whenever there is a syntax error or a type error, we need to thread and carry this information on the AST.

**Comment by banjomet** [comment]
This sounds incredibly useful and I would like to help. What files do you think I should start looking at?

**Comment by ostera** [comment]
Hej @banjomet this is a rather involved task but I'd be happy to help you get on board. 

Right now I'm trying to move away from the Menhir parser an into the `tree-sitter-erlang` parser so the first thing we'd have to do is, well, redefine the Parsetree type 🙈 &mdash; worry not! I've got something in the works that I'll be merging sometime soon and we can have this chat again then.

In the meantime, if you want to help out with the `tree-sitter-erlang` parser that'd be great. The better that gets, the better Erlang parsing Caramel will have 😄

Check it out here: https://github.com/AbstractMachinesLab/tree-sitter-erlang/

**Comment by ostera** [comment]
I've merged a preliminary Parsetree in `erl_parsetree.ml` that we can start using. It is not currently in use, but we can start migrating to it.
