### ISSUE TITLE
How does one run the compiled erlang in the README example?

### ISSUE THREAD

**Issue by drewolson** [AbstractMachinesLab/caramel#34]
I've been able to compile the [example](https://github.com/AbstractMachinesLab/caramel#examples) in the README, but when I attempt to run the generated erlang, I'm told that the function `process:make` does not exist. It seems this module is provided as part of caramel's stdlib, but it doesn't appear to be in erlang's load path. Is it expected that I somehow make this available before running my program? Should these definitions instead be inlined during compilation?

Am I missing some step that makes this "just work"?

Thanks!

**Comment by ostera** [comment]
Hi 👋🏼 -- the standard library is distributed as both typings and erlang sources, so you have to compile it and make it available in your path as follows:

```
# after unzipping the release
$ erlc ./caramel/lib/caramel/stdlib/beam/*.erl
$ erl -pa ./caramel/lib/stdlib/beam
Erlang/OTP 23 [erts-11.0.3] [source] [64-bit] [smp:64:64] [ds:64:64:10] [async-threads:1] [hipe]

Eshell V11.0.3  (abort with ^G)
1> caramel_runtime:binary_concat(<<"hello, ">>, <<"world!">>).
<<"hello, world!">>
```

Let me know how this goes :) I tried this steps when I documented them in the README (check the end of the Getting Started section) but its possible that I may have broken something too.
