### ISSUE TITLE
Large repository due to metadata

### ISSUE THREAD

**Issue by yetkinozturk** [AbstractMachinesLab/caramel#5]
Hey,

I am willing to have a look at the project and hopefully contribute to it in the future (improving my ocaml skills now :P) but one thing caught my attention.
the .git folder his huge, would you consider a cleanup?
```
du -sh caramel
184M	caramel
du -sh caramel/.git
181M	caramel/.git
```

**Comment by ostera** [comment]
Hi @yetkinozturk, sure thing! There's a branch that might be guilty, `trunk`, which is essentially the HEAD of the OCaml repo from where this was originally forked. That branch has ~20k commits in it!

I've left it there for the time being, but it should be cleaned up.

I'll have a look at it over lunch :)

**Comment by ostera** [comment]
It's been cleaned 🆗

**Comment by yetkinozturk** [comment]
ah I didn't know it has such history. Thanks 👍
