### ISSUE TITLE
problem with windows security

### ISSUE THREAD

**Issue by hgabe** [AbstractMachinesLab/caramel#52]
![caramel_defender](https://user-images.githubusercontent.com/4083664/106380953-a1b82e80-6383-11eb-9398-5e036bda847b.PNG)

wondering if its a false positive

**Comment by ostera** [comment]
That's weird! Could you try with the v0.1.0 release?

**Comment by ostera** [comment]
Any luck with v0.1 @hgabe ?

**Comment by joprice** [comment]
Apparently you can submit files that are false positives to improve their model https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by ostera** [comment]
Done! Closing this. @hgabe feel free to reopen if you've got more info to share :)

**Comment by hgabe** [comment]
ok tried the latest version does this have a repl and I cant quit the repl
