### ISSUE TITLE
Fun references of operators have the wrong arity and module name

### ISSUE THREAD

**Issue by ostera** [AbstractMachinesLab/caramel#70]
From #57 by @michallepicki:

This leads to another related issue, currently:

```ocaml
Lists.foldl ( + ) 1 [1; 2; 3]
```
generates

```erlang
lists:foldl(fun '+'/0, 1, [1 | [2 | [3 | []]]])
```
where it lacks the erlang: prefix and the arity is wrong. Not sure if this is something that should be supported right now or not.

**Comment by michallepicki** [comment]
May be related to https://github.com/AbstractMachinesLab/caramel/issues/10 fixed in https://github.com/AbstractMachinesLab/caramel/commit/1b4e6b80083920a748b9e4ebda88cb48271bd740 ? At least it may be a good starting point to dive in

**Comment by michallepicki** [comment]
This may or may not be related, fun references of regular functions (not operators) cannot be used this way:
```ocaml
let print thing = Io.format "~0tp~n" [ thing ]
let main _ =
  let transforms = [ Binary.first; Binary.last ] in
     print (Lists.map (fun g -> g "Hello World") transforms)
```

results in
```erlang
% Source code generated with Caramel.
-module(main).

-export([main/1]).
-export([print/1]).

-spec print(_) -> ok.
print(Thing) -> io:format(<<"~0tp~n">>, [Thing | []]).

-spec main(_) -> ok.
main(_) ->
  Transforms = [binary:first | [binary:last | []]],
  print(lists:map(fun
  (G) -> G(<<"Hello World">>)
end, Transforms)).
```

`fun` and the `/arity` is missing
