### ISSUE TITLE
Map Literal syntax

### ISSUE THREAD

**Issue by AeroNotix** [AbstractMachinesLab/caramel#96]
Hi,

Does Caramel support the map literal syntax? I can't find examples or documentation which point to it being available.

**Comment by michallepicki** [comment]
Hi!
OCaml records translate to Erlang maps with atom keys: https://caramel.run/manual/guides/syntax-cheatsheet.html#records

```
{ fst = 1 ; snd = "hej" }
```

**Comment by AeroNotix** [comment]
Ah, apologies. I'd read that part of the docs but must've assumed that they were mapping to Erlang _records_. Not maps!
